# Generated by Django 4.2.9 on 2024-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pin', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humid', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
