# Generated by Django 4.2.9 on 2024-03-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temp',
            table='air_readings_detailed',
        ),
    ]
