# Generated by Django 4.2.9 on 2024-03-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_temp_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={'managed': False},
        ),
    ]
