# Generated by Django 5.0.1 on 2024-01-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
